### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by MichaelAquilina** [Rob--W/display-anchors#1]
I do not have any experience working with Firefox/Chrome extensions, but I was wondering whether it would be difficult to port this to Firefox?

**Comment by Rob--W** [comment]
It is not impossible to port the extension, but it is not a deadly easy task either. There are some differences in extension APIs that can be overcome relatively easily, but the main functionality (displaying anchors without affecting styles of the page) is more complicated.

The current implementation uses shadow DOM for style isolation. This is not supported in Firefox, so I have to implement an alternative solution (e.g. reset sheets).

I have wanted a Firefox port for a while, and this issue proves that I'm not the only one, so maybe I'll publish a Firefox port in a few weeks.

**Comment by MichaelAquilina** [comment]
Great to hear! I am sure the firefox community would really appreciate it :)

**Comment by Rob--W** [comment]
Here it is: https://addons.mozilla.org/en-US/firefox/addon/display-_anchors/

**Comment by MichaelAquilina** [comment]
Awesome thanks for this! I cant seem to get the keyboard shortcut to work though....

**Comment by Rob--W** [comment]
You are probably using Firefox 51 or earlier, right?
The method that I used for capturing the shortcut only works in Firefox 52+ (https://bugzil.la/1246034). I submitted a new version (1.3) where the shortcut also works in Firefox 51- (08b9883a6589b1e4d2698fec7e266eb0470b0b8d).

**Comment by MichaelAquilina** [comment]
I am using Firefox 51 so that must be the issue. Thanks for the help @Rob--W :) I have also installed some of your other addons too btw!
