### ISSUE TITLE
Compatibility with horizontal tab %09 within anchors

### ISSUE THREAD

**Issue by grahamperrin** [Rob--W/display-anchors#10]
From <https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259671>: 

> Examples: 
> 
> <https://www.freebsd.org/cgi/man.cgi?query=loader.conf&sektion=5&manpath=FreeBSD+12.2-RELEASE#DEFAULT%09SETTINGS>
> 
> <https://www.freebsd.org/cgi/man.cgi?query=loader.conf&sektion=5&manpath=FreeBSD+13.0-RELEASE#DEFAULT%09SETTINGS>

> … problems for extensions such as: …

> – when pointed at, and when copied, the horizontal tab is missing.

**Comment by Rob--W** [comment]
This is not a bug with my extension. The source code of https://man.freebsd.org/cgi/man.cgi?query=loader.conf&sektion=5&manpath=FreeBSD+12.2-RELEASE#DEFAULT%09SETTINGS shows the following:

```html
<a name="DEFAULT%09SETTINGS" href="#end"><b>DEFAULT	SETTINGS</b></a>
```

As you can see, the value of the `id` attribute is `DEFAULT%09SETTINGS`. Although `%09` may seem like a url-encoded TAB character, it has no special meaning in the `id` attribute. It just means "percent zero nine", and is therefore rendered as such.
