### ISSUE TITLE
Maybe an "always display anchors" mode

### ISSUE THREAD

**Issue by szalapski** [Rob--W/display-anchors#11]
I wonder if I would like it to always display anchors--and if so, the display would need to be much more subtle.  Maybe just a single small "#" character or perhaps a #️⃣ character with a title.  Maybe even move it left a bit so it doesn't cover up anything following it?  

Just an idea.  Maybe I could work on it too.

**Comment by Rob--W** [comment]
That is unlikely to be helpful. Anchors are very prevalent, many pages would be annoyingly near-unusable if anchors are sprinkled through all documents.

Moreover, doing what you are asking for would require additional permissions for all websites. Not to mention the performance impact of trying to add anchors to all pages that are updated dynamically.

If you want to quickly get anchors without clicking the button, use a keyboard shortcut instead. The extension supports that already.

**Comment by szalapski** [comment]
Yep, I hear ya.  Makes sense.

I don't see a LICENSE file in this repo...interested to add it?  If it is
intended to be open source, I might suggest the MIT License.
