### ISSUE TITLE
Cannot read links in the current tab (access denied).

### ISSUE THREAD

**Issue by mb720** [Rob--W/display-anchors#3]
Hi and thanks a lot for your plugin!

I'd like to use the shortcut `Alt + Shift + A` to show all anchors on a page.
This doesn't work and I get a notification in the upper right corner of Firefox saying

> Cannot read links in the current tab (access denied).

Yet everything works fine when I click the plugin's button to show all anchors.

Firefox version is 54.0.1 (64-bit).

Plugin version is 1.3.

`uname -a` reports

> Linux marathon 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux

Let me know if I can provide any further information.

Thanks in advance!

**Comment by Rob--W** [comment]
This is a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1387506

After clicking once on the extension button, you can use the shortcut for the tab.

I can work around the bug if this is really a big issue for you. Should I?

**Comment by mb720** [comment]
Hi Rob!

Thanks for your answer.

I'd love to use the shortcut since I want to touch the mouse as rarely as possible (I'm using the great VimFx in addition).

**Comment by aspiers** [comment]
I see this happening when viewing local `file:///...` URLs on Chrome - is there a workaround to fix that?

**Comment by Rob--W** [comment]
@aspiers Visit `chrome://extensions/?id=poahndpaaanbpbeafbkploiobpiiieko` and enable the "Allow access to file URLs" option.

**Comment by aspiers** [comment]
[**@Rob--W**](https://github.com/Rob--W) commented on [April 17, 2019 4:50 PM](https://github.com/Rob--W/display-anchors/issues/3#issuecomment-484148754 "2019-04-17T15:50:42Z - Replied by Github Reply Comments"):
> [@aspiers](https://github.com/aspiers) Visit `chrome://extensions/?id=poahndpaaanbpbeafbkploiobpiiieko` and enable the "Allow access to file URLs" option.

Thanks a lot, should have thought of that!!  I suggest documenting it in the README.
