### ISSUE TITLE
(Firefox Test Pilot) Notes keyboard shortcut conflict with Display #Anchors

### ISSUE THREAD

**Issue by grahamperrin** [Rob--W/display-anchors#7]
From <https://discourse.mozilla.org/t/keyboard-shortcut-to-open-notes/17851/4?u=grahamperrin>: 

> … The Web Extension team is also working on a way to customize …

In the meantime: Notes 4.2.0 is in conflict and (in my case) Display #Anchors wins, which suits me.

**Comment by Rob--W** [comment]
That is being worked on at https://bugzilla.mozilla.org/show_bug.cgi?id=1303384
