### ISSUE TITLE
Can encodeURI conversion be added

### ISSUE THREAD

**Issue by dnknn** [Rob--W/display-anchors#9]
outdate

**Comment by Rob--W** [comment]
Why do you want to have an urlencoded fragment?

**Comment by dnknn** [comment]
![image](https://user-images.githubusercontent.com/10995302/86739057-2d751100-c068-11ea-9c5a-9a614529c6dd.png)
Because it is not ASCII character set, pasting it elsewhere may not be a URL link as a whole.

If the extension has its own conversion function, it can be used to convert by the way, it is convenient to use it when you need it.

Of course, this question is not critical, I just talk about it.

If really need to conversion, can use another extension or use online tools.
URLEncoder
https://chrome.google.com/webstore/detail/knemomiohalcaaafakbiiijddjdhcnhe

**Comment by Rob--W** [comment]
I'm willing to accept a pull request with an option (off by default) to use `encodeURI` on the fragment.

It needs to end up here:

https://github.com/Rob--W/display-anchors/blob/e863ba01d652796806f12486f014e782fadffb3b/extension/toggle-anchors.js#L165

**Comment by dnknn** [comment]
Thank you very much, But i don't understand any language code except a little bit CSS, not a developer.
It doesn't matter, I'm just passing it by the way, it's not important.
